apiVersion: apps/v1
kind: Deployment
metadata:
  name: signoz-otel-collector
  labels:
    app: signoz-otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signoz-otel-collector
  template:
    metadata:
      labels:
        app: signoz-otel-collector
    spec:
      containers:
        - name: otel-collector
          image: signoz/signoz-otel-collector:0.88.17
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 13133
              name: health
          volumeMounts:
            - name: config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          args:
            - "--config=/etc/otel-collector-config.yaml"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
