apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/postgres-limits.yaml
  - path: patches/redis-limits.yaml
  - path: patches/nats-limits.yaml
