// Debug build 时隐藏开发期常见警告，release build 保持严格检查
#![cfg_attr(
    debug_assertions,
    allow(dead_code, unused_imports, unused_variables, unused_mut,)
)]

/// Auto-generated gRPC and protobuf types.
///
/// Generated by `build.rs` → `src/proto/`.
pub mod proto;
